In [1]:
# Pandas Series
# A Pandas Series is one of the most important data structures in the Python library pandas.
# It is basically a 1-dimensional labeled array, similar to a column in a table.

In [2]:
# creating series 
import numpy as np
import pandas as pd

In [3]:
labels = ['a','b','c','d']
my_list = [10,20,30,40]
arr = np.array([10,20,30])
d = {1:10,2:20,3:30} 
pd.Series(my_list)

0    10
1    20
2    30
3    40
dtype: int64

In [4]:
pd.Series(my_list,index=labels)

a    10
b    20
c    30
d    40
dtype: int64

In [5]:
pd.Series(arr)

0    10
1    20
2    30
dtype: int64

In [6]:
pd.Series(d)

1    10
2    20
3    30
dtype: int64

In [7]:
# Data Frame
# creating dataFrame

data = {
    'Name': ['Nikita', 'Alisha', 'Gita', 'Nishan'],
    'Age': [23, 44, 23, 23],
    'City': ['Kathmandu', 'Pokhara', 'Chitwan', 'Sindhuli'],
    'Salary': [50000, 70000, 45000, 60000]
}

In [8]:
df = pd.DataFrame(data)
df

     Name  Age       City  Salary
0  Nikita   23  Kathmandu   50000
1  Alisha   44    Pokhara   70000
2    Gita   23    Chitwan   45000
3  Nishan   23   Sindhuli   60000

In [9]:
data_list = [
    ['Nikita', 23, 'Kathmandu', 50000],
    ['Alisha', 44, 'Pokhara', 70000],
    ['Gita', 23, 'Chitwan', 45000],
    ['Nishan', 23, 'Sindhuli', 60000]
]
df2 = pd.DataFrame(data_list)
df2

        0   1          2      3
0  Nikita  23  Kathmandu  50000
1  Alisha  44    Pokhara  70000
2    Gita  23    Chitwan  45000
3  Nishan  23   Sindhuli  60000

In [10]:
columns=["Name", "Age", "City", "Salary"]
df2 = pd.DataFrame(data_list, columns=columns)
df2

     Name  Age       City  Salary
0  Nikita   23  Kathmandu   50000
1  Alisha   44    Pokhara   70000
2    Gita   23    Chitwan   45000
3  Nishan   23   Sindhuli   60000

In [11]:
df2["Name"]

0    Nikita
1    Alisha
2      Gita
3    Nishan
Name: Name, dtype: str

In [12]:
df2["City"]

0    Kathmandu
1      Pokhara
2      Chitwan
3     Sindhuli
Name: City, dtype: str

In [13]:
df2[["Salary", "Name"]]

   Salary    Name
0   50000  Nikita
1   70000  Alisha
2   45000    Gita
3   60000  Nishan

In [14]:
df2["Designation"] = [
    "Software Engineer",
    "Manager",
    "Accountant",
    "Data Analyst"
]

print(df2)

     Name  Age       City  Salary        Designation
0  Nikita   23  Kathmandu   50000  Software Engineer
1  Alisha   44    Pokhara   70000            Manager
2    Gita   23    Chitwan   45000         Accountant
3  Nishan   23   Sindhuli   60000       Data Analyst

In [15]:
df2.drop("Age", axis=1, inplace= True) #axis 1 col and 0 row

In [16]:
df2.drop(0, axis =0)

     Name      City  Salary   Designation
1  Alisha   Pokhara   70000       Manager
2    Gita   Chitwan   45000    Accountant
3  Nishan  Sindhuli   60000  Data Analyst

In [17]:
df2.loc[0]

Name                      Nikita
City                   Kathmandu
Salary                     50000
Designation    Software Engineer
Name: 0, dtype: object

In [18]:
df2.loc[1]

Name            Alisha
City           Pokhara
Salary           70000
Designation    Manager
Name: 1, dtype: object

In [19]:
df2.loc[[0,1]][["City","Salary"]]

        City  Salary
0  Kathmandu   50000
1    Pokhara   70000

In [20]:
df2

     Name       City  Salary        Designation
0  Nikita  Kathmandu   50000  Software Engineer
1  Alisha    Pokhara   70000            Manager
2    Gita    Chitwan   45000         Accountant
3  Nishan   Sindhuli   60000       Data Analyst

In [21]:
df2.loc[[2,3]][["Name", "City"]]

     Name      City
2    Gita   Chitwan
3  Nishan  Sindhuli

In [22]:
# conditional Selection
df2[df2["Salary"]> 45000]

     Name       City  Salary        Designation
0  Nikita  Kathmandu   50000  Software Engineer
1  Alisha    Pokhara   70000            Manager
3  Nishan   Sindhuli   60000       Data Analyst

In [23]:
employee_data = [
    ['Nikita', 23, 'Kathmandu', 50000, 'Software Engineer'],
    ['Alisha', 44, 'Pokhara', 70000, 'Manager'],
    ['Gita', 23, 'Chitwan', 45000, 'Accountant'],
    ['Nishan', 26, 'Sindhuli', 60000, 'Data Analyst'],
    ['Rahul', 30, 'Biratnagar', 55000, 'Web Developer'],
    ['Suman', 29, 'Butwal', 52000, 'UI/UX Designer'],
    ['Priya', 27, 'Dharan', 48000, 'HR Officer'],
    ['Aman', 35, 'Janakpur', 80000, 'Project Manager'],
    ['Sneha', 24, 'Lalitpur', 47000, 'QA Engineer'],
    ['Kiran', 31, 'Bhaktapur', 65000, 'Database Admin']
]

In [24]:
columns=['Name','Age','City','Salary','Designation']
data = pd.DataFrame(employee_data, columns=columns)
data

     Name  Age        City  Salary        Designation
0  Nikita   23   Kathmandu   50000  Software Engineer
1  Alisha   44     Pokhara   70000            Manager
2    Gita   23     Chitwan   45000         Accountant
3  Nishan   26    Sindhuli   60000       Data Analyst
4   Rahul   30  Biratnagar   55000      Web Developer
5   Suman   29      Butwal   52000     UI/UX Designer
6   Priya   27      Dharan   48000         HR Officer
7    Aman   35    Janakpur   80000    Project Manager
8   Sneha   24    Lalitpur   47000        QA Engineer
9   Kiran   31   Bhaktapur   65000     Database Admin

In [25]:
data[( data["Age"]> 30)  & (data["City"] =='Bhaktapur')]

    Name  Age       City  Salary     Designation
9  Kiran   31  Bhaktapur   65000  Database Admin

In [26]:
# Missing Data
employee_data = [
    ['Nikita', 23, 'Kathmandu', 50000, 'Software Engineer'],
    ['Alisha', None, 'Pokhara', 70000, 'Manager'],
    ['Gita', 23, None, 45000, 'Accountant'],
    ['Nishan', 26, 'Sindhuli', None, 'Data Analyst'],
    ['Rahul', 30, 'Biratnagar', 55000, None]
]

In [27]:
columns =['Name', 'Age', 'City', 'Salary', 'Designation']
result= pd.DataFrame(employee_data, columns=columns)
result

     Name   Age        City   Salary        Designation
0  Nikita  23.0   Kathmandu  50000.0  Software Engineer
1  Alisha   NaN     Pokhara  70000.0            Manager
2    Gita  23.0         NaN  45000.0         Accountant
3  Nishan  26.0    Sindhuli      NaN       Data Analyst
4   Rahul  30.0  Biratnagar  55000.0                NaN

In [28]:
result.isna()

    Name    Age   City  Salary  Designation
0  False  False  False   False        False
1  False   True  False   False        False
2  False  False   True   False        False
3  False  False  False    True        False
4  False  False  False   False         True

In [29]:
result.isna().sum()

Name           0
Age            1
City           1
Salary         1
Designation    1
dtype: int64

In [30]:
result.isna().any()

Name           False
Age             True
City            True
Salary          True
Designation     True
dtype: bool

In [31]:
result

     Name   Age        City   Salary        Designation
0  Nikita  23.0   Kathmandu  50000.0  Software Engineer
1  Alisha   NaN     Pokhara  70000.0            Manager
2    Gita  23.0         NaN  45000.0         Accountant
3  Nishan  26.0    Sindhuli      NaN       Data Analyst
4   Rahul  30.0  Biratnagar  55000.0                NaN

In [32]:
result.dropna()

     Name   Age       City   Salary        Designation
0  Nikita  23.0  Kathmandu  50000.0  Software Engineer

In [33]:
result

     Name   Age        City   Salary        Designation
0  Nikita  23.0   Kathmandu  50000.0  Software Engineer
1  Alisha   NaN     Pokhara  70000.0            Manager
2    Gita  23.0         NaN  45000.0         Accountant
3  Nishan  26.0    Sindhuli      NaN       Data Analyst
4   Rahul  30.0  Biratnagar  55000.0                NaN

In [34]:
df.dropna(thresh=3)

     Name  Age       City  Salary
0  Nikita   23  Kathmandu   50000
1  Alisha   44    Pokhara   70000
2    Gita   23    Chitwan   45000
3  Nishan   23   Sindhuli   60000

In [35]:
# filling the missing data 
result.fillna(0)

     Name   Age        City   Salary        Designation
0  Nikita  23.0   Kathmandu  50000.0  Software Engineer
1  Alisha   0.0     Pokhara  70000.0            Manager
2    Gita  23.0           0  45000.0         Accountant
3  Nishan  26.0    Sindhuli      0.0       Data Analyst
4   Rahul  30.0  Biratnagar  55000.0                  0

In [37]:
values = {
    'Age': 0,
    'City': 'Unknown',
    'Salary': 10000,
    'Designation': 'Not Assigned'
}
result.fillna(value=values)

     Name   Age        City   Salary        Designation
0  Nikita  23.0   Kathmandu  50000.0  Software Engineer
1  Alisha   0.0     Pokhara  70000.0            Manager
2    Gita  23.0     Unknown  45000.0         Accountant
3  Nishan  26.0    Sindhuli  10000.0       Data Analyst
4   Rahul  30.0  Biratnagar  55000.0       Not Assigned

In [38]:
# MergingJoiningConcatination
df1 = pd.DataFrame({
    'Name': ['Nikita', 'Alisha'],
    'Age': [23, 25]
})

df2 = pd.DataFrame({
    'Name': ['Nishan', 'Rahul'],
    'Age': [26, 30]
})

result = pd.concat([df1, df2])

print(result)

     Name  Age
0  Nikita   23
1  Alisha   25
0  Nishan   26
1   Rahul   30

In [ ]:
# Pandas GroupBy and Aggregation

In [40]:
import pandas as pd
from sklearn.preprocessing import LabelEncoder

df = pd.DataFrame({
    'Name': ['Nikita Rai', 'Alisha Sharma', 'Nishan Kumar'],
    'City': ['Kathmandu', 'Pokhara', 'Kathmandu'],
    'Age': [23, 25, 26],
    'Salary': [50000, 70000, 60000],
    'Date': pd.to_datetime(['2026-01-10', '2026-02-15', '2026-03-20'])
})

# Feature Engineering
df['First_Name'] = df['Name'].apply(lambda x: x.split()[0])
df['Salary_Level'] = df['Salary'].apply(lambda x: 'High' if x > 60000 else 'Low')
df['Year'] = df['Date'].dt.year
df['Month'] = df['Date'].dt.month

# Encoding
le = LabelEncoder()
df['City'] = le.fit_transform(df['City'])

# Drop original column
df.drop(['Name', 'Date'], axis=1, inplace=True)

print(df)

ModuleNotFoundError: No module named 'sklearn'