In [1]:
# Creating a DataFrame
# Selection and indexing of Columns
# Creating a new column
# removing columns
# selecting rows
# selecting subsets of rows and columns
# conditional selection

In [2]:
import numpy as np
import pandas as pd

In [3]:
data = {
    "EmployeeID": [101, 102, 103, 104, 105, 106, 107, 108, 109, 110],
    "Name": ["Ram", "Sita", "Hari", "Gita", "Shyam", "Rita", "Mohan", "Kiran", "Asha", "Bina"],
    "Department": ["IT", "HR", "IT", "Finance", "HR", "IT", "Finance", "HR", "IT", "Finance"],
    "Age": [25, 30, 28, 35, 32, 27, 40, 29, None, 31],
    "Salary": [50000, 45000, 55000, 70000, 48000, 60000, 75000, 47000, 58000, None],
    "Experience": [2, 5, 3, 10, 6, 4, 12, 5, 3, 7],
    "City": ["Kathmandu", "Pokhara", "Kathmandu", "Biratnagar", "Pokhara",
             "Chitwan", "Biratnagar", "Pokhara", "Kathmandu", "Chitwan"],
    "JoiningDate": [
        "2022-01-15", "2020-06-20", "2021-03-10", "2018-09-05",
        "2019-11-12", "2021-07-25", "2016-04-18", "2020-02-28",
        "2022-05-01", "2019-08-14"
    ]
}

In [4]:
df = pd.DataFrame(data)

In [5]:
df["Name"]

0      Ram
1     Sita
2     Hari
3     Gita
4    Shyam
5     Rita
6    Mohan
7    Kiran
8     Asha
9     Bina
Name: Name, dtype: str

In [6]:
df[["Name","City"]]

    Name        City
0    Ram   Kathmandu
1   Sita     Pokhara
2   Hari   Kathmandu
3   Gita  Biratnagar
4  Shyam     Pokhara
5   Rita     Chitwan
6  Mohan  Biratnagar
7  Kiran     Pokhara
8   Asha   Kathmandu
9   Bina     Chitwan

In [7]:
df["LastName"]=["Rai","Gurung","Shrestha","Magar", "Timalsina","Tamang","Pandey","Magar","Rai","Nepal"]

In [8]:
df

,EmployeeID,Name,Department,Age,Salary,Experience,City,JoiningDate,LastName
0,101,Ram,IT,25.0,50000.0,2,Kathmandu,2022-01-15,Rai
1,102,Sita,HR,30.0,45000.0,5,Pokhara,2020-06-20,Gurung
2,103,Hari,IT,28.0,55000.0,3,Kathmandu,2021-03-10,Shrestha
3,104,Gita,Finance,35.0,70000.0,10,Biratnagar,2018-09-05,Magar
4,105,Shyam,HR,32.0,48000.0,6,Pokhara,2019-11-12,Timalsina
5,106,Rita,IT,27.0,60000.0,4,Chitwan,2021-07-25,Tamang
6,107,Mohan,Finance,40.0,75000.0,12,Biratnagar,2016-04-18,Pandey
7,108,Kiran,HR,29.0,47000.0,5,Pokhara,2020-02-28,Magar
8,109,Asha,IT,NaN,58000.0,3,Kathmandu,2022-05-01,Rai
9,110,Bina,Finance,31.0,NaN,7,Chitwan,2019-08-14,Nepal

In [9]:
df.drop('LastName', axis=1, inplace=True) # axis 0 is horizintal(row) axis 1 is vertical (means column)

In [10]:
df

,EmployeeID,Name,Department,Age,Salary,Experience,City,JoiningDate
0,101,Ram,IT,25.0,50000.0,2,Kathmandu,2022-01-15
1,102,Sita,HR,30.0,45000.0,5,Pokhara,2020-06-20
2,103,Hari,IT,28.0,55000.0,3,Kathmandu,2021-03-10
3,104,Gita,Finance,35.0,70000.0,10,Biratnagar,2018-09-05
4,105,Shyam,HR,32.0,48000.0,6,Pokhara,2019-11-12
5,106,Rita,IT,27.0,60000.0,4,Chitwan,2021-07-25
6,107,Mohan,Finance,40.0,75000.0,12,Biratnagar,2016-04-18
7,108,Kiran,HR,29.0,47000.0,5,Pokhara,2020-02-28
8,109,Asha,IT,NaN,58000.0,3,Kathmandu,2022-05-01
9,110,Bina,Finance,31.0,NaN,7,Chitwan,2019-08-14

In [11]:
df.drop(0, axis=0) #delete row

,EmployeeID,Name,Department,Age,Salary,Experience,City,JoiningDate
1,102,Sita,HR,30.0,45000.0,5,Pokhara,2020-06-20
2,103,Hari,IT,28.0,55000.0,3,Kathmandu,2021-03-10
3,104,Gita,Finance,35.0,70000.0,10,Biratnagar,2018-09-05
4,105,Shyam,HR,32.0,48000.0,6,Pokhara,2019-11-12
5,106,Rita,IT,27.0,60000.0,4,Chitwan,2021-07-25
6,107,Mohan,Finance,40.0,75000.0,12,Biratnagar,2016-04-18
7,108,Kiran,HR,29.0,47000.0,5,Pokhara,2020-02-28
8,109,Asha,IT,NaN,58000.0,3,Kathmandu,2022-05-01
9,110,Bina,Finance,31.0,NaN,7,Chitwan,2019-08-14

In [12]:
df

,EmployeeID,Name,Department,Age,Salary,Experience,City,JoiningDate
0,101,Ram,IT,25.0,50000.0,2,Kathmandu,2022-01-15
1,102,Sita,HR,30.0,45000.0,5,Pokhara,2020-06-20
2,103,Hari,IT,28.0,55000.0,3,Kathmandu,2021-03-10
3,104,Gita,Finance,35.0,70000.0,10,Biratnagar,2018-09-05
4,105,Shyam,HR,32.0,48000.0,6,Pokhara,2019-11-12
5,106,Rita,IT,27.0,60000.0,4,Chitwan,2021-07-25
6,107,Mohan,Finance,40.0,75000.0,12,Biratnagar,2016-04-18
7,108,Kiran,HR,29.0,47000.0,5,Pokhara,2020-02-28
8,109,Asha,IT,NaN,58000.0,3,Kathmandu,2022-05-01
9,110,Bina,Finance,31.0,NaN,7,Chitwan,2019-08-14

In [13]:
df.loc[0] #select location

EmployeeID            101
Name                  Ram
Department             IT
Age                  25.0
Salary            50000.0
Experience              2
City            Kathmandu
JoiningDate    2022-01-15
Name: 0, dtype: object

In [14]:
df.iloc[1]

EmployeeID            102
Name                 Sita
Department             HR
Age                  30.0
Salary            45000.0
Experience              5
City              Pokhara
JoiningDate    2020-06-20
Name: 1, dtype: object

In [15]:
# selecting subsets of rows and columns

In [16]:
df.loc[[0,1]]

,EmployeeID,Name,Department,Age,Salary,Experience,City,JoiningDate
0,101,Ram,IT,25.0,50000.0,2,Kathmandu,2022-01-15
1,102,Sita,HR,30.0,45000.0,5,Pokhara,2020-06-20

In [17]:
df.loc[[0,1]][["City","Name"]]

        City  Name
0  Kathmandu   Ram
1    Pokhara  Sita

In [18]:
# conditional selection 
df

,EmployeeID,Name,Department,Age,Salary,Experience,City,JoiningDate
0,101,Ram,IT,25.0,50000.0,2,Kathmandu,2022-01-15
1,102,Sita,HR,30.0,45000.0,5,Pokhara,2020-06-20
2,103,Hari,IT,28.0,55000.0,3,Kathmandu,2021-03-10
3,104,Gita,Finance,35.0,70000.0,10,Biratnagar,2018-09-05
4,105,Shyam,HR,32.0,48000.0,6,Pokhara,2019-11-12
5,106,Rita,IT,27.0,60000.0,4,Chitwan,2021-07-25
6,107,Mohan,Finance,40.0,75000.0,12,Biratnagar,2016-04-18
7,108,Kiran,HR,29.0,47000.0,5,Pokhara,2020-02-28
8,109,Asha,IT,NaN,58000.0,3,Kathmandu,2022-05-01
9,110,Bina,Finance,31.0,NaN,7,Chitwan,2019-08-14

In [19]:
# age above 30
df[df["Age"]>=30]

,EmployeeID,Name,Department,Age,Salary,Experience,City,JoiningDate
1,102,Sita,HR,30.0,45000.0,5,Pokhara,2020-06-20
3,104,Gita,Finance,35.0,70000.0,10,Biratnagar,2018-09-05
4,105,Shyam,HR,32.0,48000.0,6,Pokhara,2019-11-12
6,107,Mohan,Finance,40.0,75000.0,12,Biratnagar,2016-04-18
9,110,Bina,Finance,31.0,NaN,7,Chitwan,2019-08-14

In [20]:
df[(df["Age"] >30) & (df["City"]== "P okhara")]

,EmployeeID,Name,Department,Age,Salary,Experience,City,JoiningDate
4,105,Shyam,HR,32.0,48000.0,6,Pokhara,2019-11-12

In [21]:
# Finding Missing Data
# Removing missing data
# filling the missing data

In [22]:
df

,EmployeeID,Name,Department,Age,Salary,Experience,City,JoiningDate
0,101,Ram,IT,25.0,50000.0,2,Kathmandu,2022-01-15
1,102,Sita,HR,30.0,45000.0,5,Pokhara,2020-06-20
2,103,Hari,IT,28.0,55000.0,3,Kathmandu,2021-03-10
3,104,Gita,Finance,35.0,70000.0,10,Biratnagar,2018-09-05
4,105,Shyam,HR,32.0,48000.0,6,Pokhara,2019-11-12
5,106,Rita,IT,27.0,60000.0,4,Chitwan,2021-07-25
6,107,Mohan,Finance,40.0,75000.0,12,Biratnagar,2016-04-18
7,108,Kiran,HR,29.0,47000.0,5,Pokhara,2020-02-28
8,109,Asha,IT,NaN,58000.0,3,Kathmandu,2022-05-01
9,110,Bina,Finance,31.0,NaN,7,Chitwan,2019-08-14

In [23]:
df.isna()

,EmployeeID,Name,Department,Age,Salary,Experience,City,JoiningDate
0,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False
5,False,False,False,False,False,False,False,False
6,False,False,False,False,False,False,False,False
7,False,False,False,False,False,False,False,False
8,False,False,False,True,False,False,False,False
9,False,False,False,False,True,False,False,False

In [24]:
df.isna().sum()

EmployeeID     0
Name           0
Department     0
Age            1
Salary         1
Experience     0
City           0
JoiningDate    0
dtype: int64

In [25]:
df.isna().any()

EmployeeID     False
Name           False
Department     False
Age             True
Salary          True
Experience     False
City           False
JoiningDate    False
dtype: bool

In [26]:
df.dropna()

,EmployeeID,Name,Department,Age,Salary,Experience,City,JoiningDate
0,101,Ram,IT,25.0,50000.0,2,Kathmandu,2022-01-15
1,102,Sita,HR,30.0,45000.0,5,Pokhara,2020-06-20
2,103,Hari,IT,28.0,55000.0,3,Kathmandu,2021-03-10
3,104,Gita,Finance,35.0,70000.0,10,Biratnagar,2018-09-05
4,105,Shyam,HR,32.0,48000.0,6,Pokhara,2019-11-12
5,106,Rita,IT,27.0,60000.0,4,Chitwan,2021-07-25
6,107,Mohan,Finance,40.0,75000.0,12,Biratnagar,2016-04-18
7,108,Kiran,HR,29.0,47000.0,5,Pokhara,2020-02-28

In [32]:
df.dropna(thresh=1)

,EmployeeID,Name,Department,Age,Salary,Experience,City,JoiningDate
0,101,Ram,IT,25.0,50000.0,2,Kathmandu,2022-01-15
1,102,Sita,HR,30.0,45000.0,5,Pokhara,2020-06-20
2,103,Hari,IT,28.0,55000.0,3,Kathmandu,2021-03-10
3,104,Gita,Finance,35.0,70000.0,10,Biratnagar,2018-09-05
4,105,Shyam,HR,32.0,48000.0,6,Pokhara,2019-11-12
5,106,Rita,IT,27.0,60000.0,4,Chitwan,2021-07-25
6,107,Mohan,Finance,40.0,75000.0,12,Biratnagar,2016-04-18
7,108,Kiran,HR,29.0,47000.0,5,Pokhara,2020-02-28
8,109,Asha,IT,NaN,58000.0,3,Kathmandu,2022-05-01
9,110,Bina,Finance,31.0,NaN,7,Chitwan,2019-08-14

In [33]:
# filling the missing data

In [34]:
df.fillna(0)

,EmployeeID,Name,Department,Age,Salary,Experience,City,JoiningDate
0,101,Ram,IT,25.0,50000.0,2,Kathmandu,2022-01-15
1,102,Sita,HR,30.0,45000.0,5,Pokhara,2020-06-20
2,103,Hari,IT,28.0,55000.0,3,Kathmandu,2021-03-10
3,104,Gita,Finance,35.0,70000.0,10,Biratnagar,2018-09-05
4,105,Shyam,HR,32.0,48000.0,6,Pokhara,2019-11-12
5,106,Rita,IT,27.0,60000.0,4,Chitwan,2021-07-25
6,107,Mohan,Finance,40.0,75000.0,12,Biratnagar,2016-04-18
7,108,Kiran,HR,29.0,47000.0,5,Pokhara,2020-02-28
8,109,Asha,IT,0.0,58000.0,3,Kathmandu,2022-05-01
9,110,Bina,Finance,31.0,0.0,7,Chitwan,2019-08-14