In [1]:
import numpy as np
import pandas as pd

In [25]:
employees=pd.DataFrame({
    'employee_id':[1,2,3,4,5],
    'name':['John', 'Anna','Peter','linda','Bob'],
    'department':['HR','IT','Finance', 'IT','HR']
})
salaries =pd.DataFrame({
    'employee_id':[1,2,3,6,7],
    'salary':[4000,5000,6000,5400,24900],
    'bonus':[5000,44,3,22,33]
})

In [3]:
# Merging 2 dataframes
# concationation of 2 dataframes
# joining of 2 dataframes

In [11]:
employees

   employee_id   name department
0            1   John         HR
1            2   Anna         IT
2            3  Peter    Finance
3            4  linda         IT
4            5    Bob         HR

In [16]:
salaries

   employee_id  salary  bonus
0            1    4000   5000
1            2    5000     44
2            3    6000      3
3            6    5400     22
4            7   24900     33

In [17]:
pd.merge(employees,salaries)

   employee_id   name department  salary  bonus
0            1   John         HR    4000   5000
1            2   Anna         IT    5000     44
2            3  Peter    Finance    6000      3

In [19]:
pd.merge(employees,salaries,on='employee_id', how='inner')

   employee_id   name department  salary  bonus
0            1   John         HR    4000   5000
1            2   Anna         IT    5000     44
2            3  Peter    Finance    6000      3

In [20]:
pd.merge(employees,salaries,on='employee_id', how='outer')

   employee_id   name department   salary   bonus
0            1   John         HR   4000.0  5000.0
1            2   Anna         IT   5000.0    44.0
2            3  Peter    Finance   6000.0     3.0
3            4  linda         IT      NaN     NaN
4            5    Bob         HR      NaN     NaN
5            6    NaN        NaN   5400.0    22.0
6            7    NaN        NaN  24900.0    33.0

In [21]:
pd.merge(employees,salaries,on='employee_id', how='left')

   employee_id   name department  salary   bonus
0            1   John         HR  4000.0  5000.0
1            2   Anna         IT  5000.0    44.0
2            3  Peter    Finance  6000.0     3.0
3            4  linda         IT     NaN     NaN
4            5    Bob         HR     NaN     NaN

In [22]:
pd.merge(employees,salaries,on='employee_id', how='right')

   employee_id   name department  salary  bonus
0            1   John         HR    4000   5000
1            2   Anna         IT    5000     44
2            3  Peter    Finance    6000      3
3            6    NaN        NaN    5400     22
4            7    NaN        NaN   24900     33

In [26]:
df

,EmployeeID,Name,Department,Age,Salary,Experience,City,JoiningDate
0,101,Ram,IT,25.0,50000.0,2,Kathmandu,2022-01-15
1,102,Sita,HR,30.0,45000.0,5,Pokhara,2020-06-20
2,103,Hari,IT,28.0,55000.0,3,Kathmandu,2021-03-10
3,104,Gita,Finance,35.0,70000.0,10,Biratnagar,2018-09-05
4,105,Shyam,HR,32.0,48000.0,6,Pokhara,2019-11-12
5,106,Rita,IT,27.0,60000.0,4,Chitwan,2021-07-25
6,107,Mohan,Finance,40.0,75000.0,12,Biratnagar,2016-04-18
7,108,Kiran,HR,29.0,47000.0,5,Pokhara,2020-02-28
8,109,Asha,IT,NaN,58000.0,3,Kathmandu,2022-05-01
9,110,Bina,Finance,31.0,NaN,7,Chitwan,2019-08-14

In [27]:
df1 = pd.DataFrame({
    "Name": ["Ram", "Sita"],
    "Age": [25, 30]
})

In [28]:
df2 = pd.DataFrame({
    "Name": ["Hari", "Gita"],
    "Age": [28, 27]
})

In [29]:
pd.concat([df1,df2])

   Name  Age
0   Ram   25
1  Sita   30
0  Hari   28
1  Gita   27

In [31]:
pd.concat([df1,df2], axis=1)

   Name  Age  Name  Age
0   Ram   25  Hari   28
1  Sita   30  Gita   27